- daemon/src/gpu_controller.rs
This fixes the panic on parsing gpu and memory clock/voltage table because apparently the casing of "MHz" and "mV" is not guaranteed.
> Fix the parsing of gpu and memory clk/voltage table

- README.md
- lact-gui/src/app/root_stack/info_page/mod.rs
- lact-gui/src/app/root_stack/info_page/vulkan_info/mod.rs
- lact-gui/src/app/root_stack/mod.rs
- lact-gui/src/app/root_stack/oc_page/clocks_frame.rs
- lact-gui/src/app/root_stack/oc_page/mod.rs
- lact-gui/src/app/root_stack/oc_page/performance_level_frame.rs
- lact-gui/src/app/root_stack/oc_page/power_cap_frame.rs
- lact-gui/src/app/root_stack/oc_page/stats_frame.rs
- lact-gui/src/app/root_stack/thermals_page/mod.rs
This PR improves the design of all pages by adding standard padding around elements, section labels and overall makes everything look cleaner.
It also cleans up the code by re-using functions for standard Grid and Box designs.
Before:
| GPU info                                     | Overclocking                                 | Fan control                                 |
|----------------------------------------------|----------------------------------------------|---------------------------------------------|
|![image](https://user-images.githubusercontent.com/22796665/221357224-21163f94-1afd-4bb8-96bd-24f9ce1816ce.png)|![image](https://user-images.githubusercontent.com/22796665/221357297-9c03bcb5-0742-459b-bffb-9e75c93df25b.png)|![image](https://user-images.githubusercontent.com/22796 …
> UI design improvements

- lact-client/src/lib.rs
- lact-daemon/src/config.rs
- lact-daemon/src/server/gpu_controller/mod.rs
- lact-daemon/src/server/handler.rs
- lact-daemon/src/server/mod.rs
- lact-gui/src/app/mod.rs
- lact-schema/src/request.rs
Implements #164 
The goal of  this PR is to have a confirmation dialog that the user has to click before the settings are saved onto disk. This is useful because when tweaking some settings (especially memory frequency), it's possible to crash your system, and if the settings are saved right away you end up with a soft-bricked system that will apply the broken settings on the next daemon start.
> feat: settings confirmation

- lact-gui/src/app/root_stack/thermals_page/fan_curve_frame/mod.rs
Fixed a bug where if all points were deleted on the fan curve, it wouldn't be possible to re-add more points. Also fixed a bug when no points were present on the curve it would not expand horizontally.
> fix: inability to add points to an empty fan curve

- lact-gui/Cargo.toml
lact-daemon with default features depends on drm, which breaks build without drm.
> fix: allow gui build without drm

- Makefile
- pkg/recipes/lact/recipe.yml
This allows for packaging tooling to use the Makefile properly.
> fix: Use DESTDIR properly in the Makefile and introduce PREFIX

- res/lactd.service
The lact daemon is usable in a command-line environment, since it can be interfaced with via the command line. As it's useful in headless setups, alter the systemd service unit to permit it.
> fix: set lactd to run without requiring graphical mode

- clippy.toml
- lact-daemon/src/server/gpu_controller/mod.rs
> feat: set the GPU to the lowest power state before applying a power limit if current consumption exceeds the new limit

- lact-gui/src/app/root_stack/info_page/vulkan_info/feature_window/mod.rs
- lact-gui/ui/vulkan_features_window.blp
Allows closing the VulkanFeaturesWindow with `ESC`. Since the search entry has the focus by default, and thus the window cannot receive the `ESC` shortcut, I added a workaround using the `stop_search` signal.
> feat: close VulkanFeaturesWindow with shortcut

- Cargo.lock
- README.md
- lact-daemon/src/server/gpu_controller/fan_control.rs
- lact-daemon/src/server/gpu_controller/mod.rs
- lact-gui/src/app/root_stack/oc_page/clocks_frame.rs
- lact-schema/Cargo.toml
- lact-schema/src/lib.rs
https://github.com/ilya-zlobintsev/LACT/issues/229
https://github.com/ilya-zlobintsev/LACT/issues/235
> feat: add support for custom fan curves and static fan speed on RDNA3

- README.md
It's been in GURU (official repository maintained by Gentoo users) for a few months.
> doc: add Gentoo installation

- lact-daemon/src/server/gpu_controller/mod.rs
- lact-gui/src/app/root_stack/oc_page/gpu_stats_section.rs
- lact-gui/ui/oc_page/gpu_stats_section.blp
- lact-schema/src/lib.rs
Some AMD APUs/GPUs has the Average Clock and the Current Clock, the AMDGPU driver reports the Average Clock in `AMDGPU_INFO_SENSOR_GFX_SCLK` and hwmon.  
This PR gets the Current clock from `gpu_metrics` and displays it.
ref: https://gitlab.freedesktop.org/drm/amd/-/issues/2747
> feat: display current_gfxclk if available

- res/lact-daemon-openrc
LACT daemon can work standalone on non-systemd distribution.
This is the example of service that is run in init environment similar to what is required for `sddm` / `gdm` which usually start the desktop session. It is possible to remove some of dependencies in case different configuration is required.
> LACT OpenRC support

- lact-gui/src/app/info_row.rs
- lact-gui/ui/info_row.blp
- lact-gui/ui/software_page.blp
Make InfoRow labels not selectable by default. Allow an override of the attribute in the template (for Software tab for example).
Motivation:
GTK will place the blinking cursor on the first selectable label of a view/tab. Placing the cursor on dynamic info like the current GPU Core Clock will show the cursor jumping around as the number of digits change a lot (best seen in the OC tab).
As the selection of a label is discarded on update of a label (which happens multiple times a second for a lot of the OC and Thermals values) the cursor acts as a visual distraction rather than a feature.
Demonstration of the issue:
> fix: avoid selectable labels for dynamic info

- Cargo.lock
- lact-client/src/lib.rs
- lact-daemon/src/server/gpu_controller/mod.rs
- lact-daemon/src/server/handler.rs
- lact-daemon/src/server/mod.rs
- lact-gui/src/app/mod.rs
- lact-schema/Cargo.toml
- lact-schema/src/response.rs
- lact-schema/src/tests.rs
Hi, Dear @ilya-zlobintsev thank you for amazing peace of open source software!
A few key points about this PR.
1. .context calls are added almost everywhere to make debugging issues easier
2. serde-error is added as dependency to produce nicer error backtraces
3. A weird bug fix for RX 7900 XTX
> RX 7900 Fixes and refactoring for error reporting

- lact-gui/ui/oc_page/gpu_stats_section.blp
Hi, @ilya-zlobintsev a small fix, I hope it would be useful!
Before:
After:
> fix: Fix statistics jumping around in GUI

- lact-gui/src/app/root_stack/oc_page/gpu_stats_section.rs
Hi, @ilya-zlobintsev  I understand, that this is purely subjective, but looking at Mhz and Voltage jumping around makes my eyes dizzy.
Before:
After (+#280):
> fix: Consistently format GPU statistics

- lact-gui/src/app/info_row.rs
- lact-gui/src/app/mod.rs
- lact-gui/src/app/root_stack/info_page/hardware_info.rs
- lact-gui/ui/info_page/hardware_info_section.blp
- lact-gui/ui/info_row.blp
Should add clarity for cases like https://github.com/ilya-zlobintsev/LACT/issues/285
> feat: clearer gpu/card model separation

- lact-client/src/lib.rs
- lact-daemon/src/config.rs
- lact-daemon/src/server/gpu_controller/mod.rs
- lact-daemon/src/server/handler.rs
- lact-daemon/src/server/mod.rs
- lact-gui/src/app/mod.rs
- lact-gui/src/app/root_stack/thermals_page/fan_curve_frame/mod.rs
- lact-gui/src/app/root_stack/thermals_page/mod.rs
- lact-schema/src/lib.rs
- lact-schema/src/request.rs
- lact-schema/src/tests.rs
https://github.com/ilya-zlobintsev/LACT/issues/291
This PR adds 2 new options to fan control with a custom curve (only for RDNA2 and older, this is not exposed via PMFW on RDNA3):
- Spindown delay - when a temperature (and the calculated fan speed) is lower than the previous reading, delay actually changing the fan speed for the specified duration, and re-check if it is still needed after it.
- Speed change threshold - changes in temperature lower than this value will not affect the fan speed. This is helpful to avoid needlessly changing the PWM value for 1-2 degree changes.
> feat: fan control hysteresis

- res/lact-daemon-openrc
> lact-daemon-openrc: Support setups without merged usr

- lact-gui/src/app/mod.rs
Lact v0.5.4 and master press 'Enable Overclocking' button will panic, output:
```
thread 'main' panicked at lact-gui/src/app/mod.rs:765:27:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This commit fixes this issue:
> fix: fix press 'Enable Overclocking' will panic

- Cargo.lock
- Cargo.toml
- lact-gui/src/app/root_stack/oc_page/mod.rs
- lact-gui/src/app/root_stack/oc_page/performance_frame.rs
- lact-gui/src/app/root_stack/oc_page/power_profile/mod.rs
- lact-gui/src/app/root_stack/oc_page/power_profile/power_profile_component_grid.rs
- lact-gui/ui/oc_page/power_profile/power_profile_component_grid.blp
Shows detailed value info from the current power profile. First part of #328, the values are parsed but are not editable for now.
Looks like this on RDNA2 (detailed power profile format):
And like this on Pre-RDNA (simple power profile format):
> feat: show detailed power profile information

- lact-daemon/src/server/gpu_controller/mod.rs
- lact-gui/src/app/graphs_window/mod.rs
- lact-gui/src/app/mod.rs
- lact-gui/src/app/root_stack/oc_page/clocks_frame.rs
- lact-gui/src/app/root_stack/oc_page/clocks_frame/adjustment_row.rs
- lact-gui/src/app/root_stack/oc_page/gpu_stats_section.rs
- lact-gui/src/app/root_stack/oc_page/mod.rs
- lact-gui/ui/oc_page/clocks_frame/adjustment_row.blp
- lact-schema/src/lib.rs
Resolves confusion in #363 
This only changes how the values are shown in the UI, the daemon (including config file) still operates with physical values.
> feat: show effective VRAM clockspeed in the GUI on GDDR6 

- Cargo.toml
Before
```
❯ ls -lah target/release/lact         
-rwxr-xr-x 2 codemonkey codemonkey 6.9M Oct 22 18:45 target/release/lact
```
After
```
❯ ls -lah target/release/lact
-rwxr-xr-x 2 codemonkey codemonkey 6.4M Oct 22 18:46 target/release/lact
```
> Set codegen-units=1 to decrease binary size in release

- lact-gui/ui/info_row.blp
Small change to stop chips with every single throttling flag enabled from causing a comically-oversized >20k pixel wide window to spawn:
We simply tell GTK to ellipsize the text if it won't fit. This could probably use a little bit of margin on the left (it runs into the `Throttling:` label a tad) but it does the job, and there aren't many systems this affects.
> make throttling flags ellipsized to avoid massively oversized window

- Cargo.lock
- lact-gui/Cargo.toml
Decreases size by about 0.1 MB, while reducing compilation time
> chore: remove unused Cargo features

- API.md
After addition of profiles API became much more relevant (for an average user).
On Windows people often have different profiles for different games and (I believe) Adrenaline allows you to change them automatically.
My (recently transitioned to Linux) friend wasn't able to figure out how to use API to change profiles.
So I decided to add it to docs.
I'm thinking about writing short guide how to set it up with Steam/Heroic if you are ok with it give me a green light.
> Minor API documentation change, added example how to change profile.

- lact-daemon/src/server/gpu_controller/amd.rs
- lact-gui/src/app/pages/oc_page/mod.rs
- lact-gui/src/app/pages/oc_page/power_states/power_states_frame.rs
- lact-gui/src/app/pages/oc_page/power_states/power_states_list.rs
Fixes #421 after a regression in #340 
Tested to work on a 6900XT
> fix: apply pstates correctly when clocks settings are used

- Cargo.lock
- lact-daemon/Cargo.toml
- lact-daemon/src/server/gpu_controller/amd.rs
- lact-daemon/src/server/handler.rs
- pkg/recipes/lact-headless/recipe.yml
- pkg/recipes/lact-libadwaita/recipe.yml
- pkg/recipes/lact/recipe.yml
- rust-toolchain.toml
`libdrm_amdgpu_sys 0.8.0` supports dynamic loading.  
Now `LACT` supports GPUs from multiple vendors, so dynamic loading would be better.
> Dynamic loading of libdrm and libdrm_amdgpu

- Cargo.lock
- Cargo.toml
- lact-daemon/Cargo.toml
- lact-daemon/benches/daemon.rs
- lact-gui/Cargo.toml
- lact-gui/src/app/graphs_window/mod.rs
- lact-gui/src/app/graphs_window/plot/imp.rs
- lact-gui/src/app/graphs_window/plot/render_thread.rs
- lact/Cargo.toml
- lact/benches/bench.rs
There are 2 major issues with supersampling when rendering the plot:
- Rendering the plot texture itself is slow, taking ~30ms to render a 1080p plot with 4x supersampling. Even though this is done in a background thread, it's still a significant amount of system resources used just to render the plots
- With the GTK vulkan backend, which is the default on recent versions, drawing and downscaling the texture is exceedingly slow. At least with nvidia drivers (i was not able to confirm this happening on other drivers), maximizing the graphs window makes the entire system lag, with a profiler pointing to most of the time being spent on vulkan texture allocation calls. Which makes sense, as it's allocating textures of extremely high resolutions due to 4x supersampling. GTK's old GL backend …
> perf: disable plot supersampling, add plot render benchmarks

- README.md
Add fragment so that link jumps to section explaining why there is no universal package format
> doc: Update link README.md

- lact-daemon/src/server/gpu_controller.rs
- lact-daemon/src/server/gpu_controller/amd.rs
- lact-daemon/src/server/gpu_controller/intel.rs
- lact-daemon/src/server/gpu_controller/nvidia.rs
- lact-daemon/src/server/handler.rs
- lact-daemon/src/server/system.rs
- lact-daemon/src/suspend.rs
Fixes #493 and improves the reliability of fan control tasks after GPU reload events (such as suspend/resume).
> fix: reliably cleanup old fan control tasks on gpu reload events, limit number of fan control retry attempts

- README.md
- docs/API.md
- docs/CONFIG.md
- lact-daemon/src/config.rs
- lact-daemon/src/server.rs
- lact-daemon/src/snapshots/lact_daemon__config__tests__parse_doc.snap
- lact-daemon/src/socket.rs
These changes should make permissions configuration clearer:
- The `admin_groups` field is replaced with a `admin_group`. Previously only the first group that existed on the system in this array was used, which is not very clear behaviour. Existing group configuration will be automatically migrated to the new field.
- A new `admin_user` field is added. It directly sets the owner of the lact socket. This setting coexists with the group setting, and any user who is either `admin_user` or in the `admin_group` group will be able to access it. The field is not set by default.
> feat: update socket permissions configuration, add admin_user field

- res/device_ids.json
```
$ lact cli info
GPU 1002:744C-148C:2422-0000:03:00.0:
=====================================
GPU Model: AMD Radeon RX 7900 XTX (0x1002:0x744C:0xC8)
Card Manufacturer: Tul Corporation / PowerColor (0x148C)
Card Model: PowerColor RX 7900 XTX Red Devil (0x2422)
Driver Used: amdgpu
VBIOS Version: 022.001.002.009.000001 [2022/11/21 22:47]
VRAM Size: 24560 MiB
GPU Family: GC 11.0.0
ASIC Name: GFX1100/Navi31
Compute Units: 96
VRAM Type: GDDR6
VRAM Manufacturer: samsung
Theoretical VRAM Bandwidth: 959
L1 Cache (Per CU): 32 KiB
L2 Cache: 6144 KiB
L3 Cache: 96 MiB
Resizeable bar: Enabled
CPU Accessible VRAM: 24560
Link Speed: 16.0 GT/s PCIe x16
```
> chore: add PowerColor RX 7900 XTX Red Devil to database

- lact-daemon/Cargo.toml
- lact-daemon/build.rs
- lact-daemon/src/bindings.rs
- lact-daemon/src/server/gpu_controller.rs
- lact/Cargo.toml
to fix loongson3 and loongarch64 architecture build
> chore(lact-daemon): make nvidia bindgen feature as optional

- docs/API.md
- lact-client/src/lib.rs
- lact-daemon/src/config.rs
- lact-daemon/src/server.rs
- lact-daemon/src/server/gpu_controller.rs
- lact-daemon/src/server/gpu_controller/amd.rs
- lact-daemon/src/server/gpu_controller/fan_control.rs
- lact-daemon/src/server/gpu_controller/intel.rs
- lact-daemon/src/server/gpu_controller/nvidia.rs
- lact-daemon/src/server/handler.rs
- lact-daemon/src/tests/mod.rs
- lact-gui/src/app.rs
- lact-schema/Cargo.toml
- lact-schema/src/config.rs
- lact-schema/src/lib.rs
- lact-schema/src/request.rs
Instead of having various `set_` API requests for different options, there is now a pair of `GetGpuConfig`/`SetGpuConfig` calls which send the whole GPU config over. This simplifies the API and also solidifies the config format as the single schema instead of having separate structs for different calls.
This also has a consequence of the UI applying all the settings in a single API request, and the confirmation dialog will now revert non-clocks related settings as well if not confirmed.
Old API calls are kept for compatibility.
> feat: new GPU config socket API

- lact-gui/src/app.rs
- lact-gui/src/app/ext.rs
- lact-gui/src/app/pages/oc_page/gpu_stats_section.rs
Normal:
Stretched window:
Intel iGPU with few stats:
> chore: put the OC page stats into a FlowBox, hide unavailable stats

- docs/CONFIG.md
- lact-daemon/src/config.rs
- lact-daemon/src/server/gpu_controller/amd.rs
- lact-daemon/src/server/gpu_controller/nvidia.rs
- lact-daemon/src/snapshots/lact_daemon__config__tests__parse_doc.snap
- lact-gui/src/app/pages/thermals_page.rs
- lact-gui/src/app/pages/thermals_page/fan_curve_frame.rs
- lact-schema/src/config.rs
- lact-schema/src/lib.rs
This allows zero RPM to be used on Nvidia with a custom fan curve using the same workaround as the FanControl windows application: https://github.com/Rem0o/FanControl.Releases/wiki/Nvidia-30%25-and-0-RPM
> feat: zero RPM support on nvidia via automatic fan mode threshold temp

- lact-daemon/src/server/opencl.rs
On the OpenCL driver that do not support `CL_DEVICE_PCI_BUS_INFO_KHR`, such as ROCm, an error will be returned in the middle of the loop, and the OpenCL information for the second and subsequent GPU will not be detected correctly.  
This PR fixes that.
> fix: do not return an error in the middle of a loop

- Makefile
```shell
fruzitent@archlinux ~/d/LACT (master)> touch uninstall
fruzitent@archlinux ~/d/LACT (master)> make uninstall
make: 'uninstall' is up to date.
fruzitent@archlinux ~/d/LACT (chore/add-phony)> make uninstall
rm //usr/local/bin/lact
rm: cannot remove '//usr/local/bin/lact': No such file or directory
make: *** [Makefile:40: uninstall] Error 1
```
Ref: https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html
> chore: use PHONY targets

- lact-gui/src/app/apply_revealer.rs
- lact-gui/src/app/pages/oc_page/clocks_frame.rs
- Add a note explaining what the options do and their limitations. This should help avoid confusion by users with behaviour such as #602. It also mentions the psuedo-undervolting added in #486.
- The "Show all P-States" toggle no longer gets reset when applying settings
> chore: Nvidia OC UX improvements

- lact-gui/src/app.rs
- lact-gui/src/app/graphs_window/mod.rs
- lact-gui/src/config.rs
Previously the plots were configured globally for all GPUs, which lead to stats which are present on one GPU but not the other to get removed from the plot when switching GPUs. Now the plots are stored per-GPU, which avoids the issue.
Note: this will reset existing custom plot configs.
> feat: store plot configs per-gpu

- lact-daemon/src/server.rs
- lact-daemon/src/socket.rs
> feat: run socket chown as a host command from flatbox to work around apparmor restrictions

- README.md
I installed this on bazzite today and had issues with the systemd service not working because of a flatpak sandboxing and kept asking me to reinstall the systemd service every reboot, I installed with ujust and it just worked
> Add Bazzite to Readme

- Cargo.lock
- Cargo.toml
- flatpak/generated-sources.json
- lact-gui/Cargo.toml
- lact-gui/i18n.toml
- lact-gui/i18n/en/lact_gui.ftl
- lact-gui/i18n/uk/lact_gui.ftl
- lact-gui/src/app.rs
- lact-gui/src/app/confirmation_dialog.rs
- lact-gui/src/app/header.rs
- lact-gui/src/app/info_row.rs
- lact-gui/src/app/msg.rs
- lact-gui/src/app/pages/info_page.rs
- lact-gui/src/app/pages/oc_page.rs
- lact-gui/src/app/pages/oc_page/clocks_frame.rs
- lact-gui/src/app/pages/oc_page/clocks_frame/adjustment_row.rs
- lact-gui/src/app/pages/oc_page/gpu_stats_section.rs
- lact-gui/src/app/pages/oc_page/performance_frame.rs
- lact-gui/src/app/pages/oc_page/power_cap_section.rs
- lact-gui/src/app/pages/oc_page/power_states/power_states_frame.rs
- lact-gui/src/app/pages/oc_page/power_states/power_states_list.rs
- lact-gui/src/app/pages/software_page.rs
- lact-gui/src/app/pages/thermals_page.rs
- lact-gui/src/lib.rs
- lact-schema/Cargo.toml
- lact-schema/i18n.toml
- lact-schema/i18n/en/lact_schema.ftl
- lact-schema/src/i18n.rs
- lact-schema/src/lib.rs
This PR adds localization support. Translations are stored under the `i18n` directories in subcrates in the fluent translation format, and are loaded based on system locale.
Most UI labels have been moved to strings, but some are still hardcoded: for example the app menu names inside of relm's `menu!` macro cannot currently accept non-literals
> feat: WIP localization support

- flatpak/startup.sh
Missed this for Flatpak in #760
Using the cli with Flatpak outputs:
```sh
$ flatpak run io.github.ilya_zlobintsev.LACT cli profile set "Balanced"
/run/lactd.sock exists, skipping setup prompt
Balanced
```
Thanks
> fix(flatpak): don't output startup success for flatpak cli
