ilya-zlobintsev/LACT

daemon/Cargo.toml

fixes compilation error see https://github.com/vulkano-rs/vulkano/issues/1464

update vulkano to v0.20

---

README.md
daemon/Cargo.toml
daemon/src/daemon_connection.rs
daemon/src/gpu_controller.rs
daemon/src/lib.rs
gui/src/app.rs
gui/src/app/root_stack/oc_page.rs
gui/src/app/root_stack/oc_page/power_cap_frame.rs
gui/src/app/root_stack/oc_page/power_profile_frame.rs
gui/src/app/root_stack/oc_page/stats_grid.rs
gui/src/main.rs

So we can use abstract sockets and not worry about file permissions or cleaning up the socket. Buffer read code may need some work

Changed sockets to nix crate

---

Cargo.lock
lact-daemon/Cargo.toml
lact-daemon/src/config.rs
lact-daemon/src/server/gpu_controller/mod.rs
lact-daemon/src/server/handler.rs
lact-gui/src/app/mod.rs
lact-gui/src/app/root_stack/info_page/mod.rs
lact-gui/src/app/root_stack/oc_page/clocks_frame.rs
lact-schema/Cargo.toml
lact-schema/src/request.rs

feat: voltage offset support, fixes for rx 6000 series format

---

.github/workflows/rust.yml
Cargo.lock
README.md
lact-daemon/Cargo.toml
lact-daemon/src/server/gpu_controller/mod.rs
lact-gui/src/app/root_stack/info_page/mod.rs
lact-schema/src/lib.rs
lact/Cargo.toml
pkg/recipes/lact/recipe.yml

This adds new GPU information fetched with the https://github.com/Umio-Yasuno/libdrm-amdgpu-sys-rs library

feat: add drm info

---

lact-daemon/src/config.rs
lact-daemon/src/server/gpu_controller/mod.rs
lact-daemon/src/server/handler.rs

See https://github.com/ilya-zlobintsev/LACT/issues/129#issuecomment-1475245189

feat: add support for not cleaning up clocks table on shutdown

---

lact-client/src/lib.rs
lact-daemon/src/config.rs
lact-daemon/src/server/gpu_controller/mod.rs
lact-daemon/src/server/handler.rs
lact-daemon/src/server/mod.rs
lact-gui/src/app/mod.rs
lact-gui/src/app/root_stack/thermals_page/fan_curve_frame/mod.rs
lact-gui/src/app/root_stack/thermals_page/mod.rs
lact-schema/src/lib.rs
lact-schema/src/request.rs

Added static fan control option

---

Makefile

As per https://aur.archlinux.org/packages/lact#comment-945155

Systemd service not executable

---

README.md

https://github.com/ilya-zlobintsev/LACT/issues/216

doc: add socket permission notes to README

---

lact-daemon/src/server/gpu_controller/mod.rs

The `fd` for `AMDGPU::DeviceHandle` may require a write option when used for GUI context.
https://docs.rs/libdrm_amdgpu_sys/latest/libdrm_amdgpu_sys/AMDGPU/struct.DeviceHandle.html#method.init
```
2024-02-10T02:25:29.617592Z  INFO lact_gui: could not connect to socket: Could not connect to daemon: socket file not found
2024-02-10T02:25:29.617625Z  INFO lact_gui: using a local daemon
2024-02-10T02:25:29.667732Z  INFO lact_daemon::server::handler: initialized 2 GPUs
(process:3616): Gtk-WARNING **: 11:25:29.671: Unknown key gtk-modules in /home/coelacanth/.config/gtk-4.0/settings.ini
amdgpu: amdgpu_bo_cpu_map failed. (-13)
radeonsi: can't create radeon_winsys_ctx
radeonsi: Failed to create a context.
amdgpu: amdgpu_bo_cpu_map failed. (-13)
radeonsi: can't create radeon_winsys_ctx
radeonsi: …
```

fix: Fix amdgpu_bo_cpu_map failed error in embedded mode

---

.github/workflows/build-packages.yaml
.pkger.yml

https://github.com/ilya-zlobintsev/LACT/issues/246

feat: add package signing for fedora packages

---

Cargo.lock
lact-daemon/Cargo.toml
lact-daemon/src/server/gpu_controller/mod.rs
lact-gui/src/app/root_stack/info_page/hardware_info.rs
lact-schema/src/lib.rs

See https://github.com/ilya-zlobintsev/LACT/issues/285

feat: use drm for getting the gpu device name when possible

---

lact-daemon/src/server/gpu_controller/mod.rs

Fixes https://github.com/ilya-zlobintsev/LACT/issues/294

fix: set performance level after the clocks table, reset it to auto before applying a custom value

---

.github/workflows/build-packages.yaml
.pkger.yml
pkg/images/ubuntu-2404/Dockerfile
pkg/recipes/lact-headless/recipe.yml
pkg/recipes/lact/recipe.yml

Closes https://github.com/ilya-zlobintsev/LACT/issues/331

pkg: add ubuntu 24.04 package

---

lact-gui/src/app/graphs_window/mod.rs
lact-gui/src/app/graphs_window/plot/imp.rs
lact-gui/ui/graphs_window.blp

feat: add fan speed plot

---

Cargo.lock
Cargo.toml
lact-daemon/src/server/gpu_controller/mod.rs

Should help with brittle RDNA3 firmware described in #329

fix: defer committing clocks/fan settings changes until all the values have been written

---

lact-gui/src/app/mod.rs

Fixes https://github.com/ilya-zlobintsev/LACT/issues/362

feat: use ScrolledWindow for initramfs output when enabling/disabling oc

---

.github/workflows/build-packages.yaml
.pkger.yml
lact-gui/src/lib.rs
pkg/images/rhel-8/Dockerfile
pkg/images/rhel-9/Dockerfile
pkg/recipes/lact-headless/recipe.yml

https://github.com/ilya-zlobintsev/LACT/issues/377

feat: add headless packages for RHEL (via Rocky Linux)

---

.github/workflows/build-packages.yaml
.pkger.yml
pkg/images/fedora-41/Dockerfile
pkg/recipes/lact-headless/recipe.yml
pkg/recipes/lact-libadwaita/recipe.yml
pkg/recipes/lact/recipe.yml

Closes https://github.com/ilya-zlobintsev/LACT/issues/396

pkg: add fedora 41 package

---

lact-daemon/src/server/gpu_controller/amd.rs

Fixes https://github.com/ilya-zlobintsev/LACT/issues/455

feat: read vram clockspeed from drm

---

lact-daemon/src/server/handler.rs
lact-gui/src/app.rs
lact-gui/src/app/pages/oc_page.rs
lact-gui/src/app/pages/oc_page/power_states/power_states_frame.rs
lact-gui/ui/oc_page/power_states_frame.blp

Should resolve most of what people are experiencing in https://github.com/ilya-zlobintsev/LACT/issues/452

fix: avoid setting pstates unless explicitly enabled in the gui

---

Cargo.lock
lact-daemon/src/config.rs
lact-daemon/src/lib.rs
lact-daemon/src/server/gpu_controller/amd.rs
lact-daemon/src/server/gpu_controller/nvidia.rs
lact-daemon/src/server/handler.rs
lact-daemon/src/tests/snapshots/lact_daemon__tests__amd__hd7870.snap
lact-daemon/src/tests/snapshots/lact_daemon__tests__amd__r9-280.snap
lact-daemon/src/tests/snapshots/lact_daemon__tests__amd__rx5500xt.snap
lact-daemon/src/tests/snapshots/lact_daemon__tests__amd__rx5700xt.snap
lact-daemon/src/tests/snapshots/lact_daemon__tests__amd__rx580.snap
lact-daemon/src/tests/snapshots/lact_daemon__tests__amd__rx6600.snap
lact-daemon/src/tests/snapshots/lact_daemon__tests__amd__rx6600xt.snap
lact-daemon/src/tests/snapshots/lact_daemon__tests__amd__rx6900xt.snap
lact-daemon/src/tests/snapshots/lact_daemon__tests__amd__rx7700s.snap
lact-daemon/src/tests/snapshots/lact_daemon__tests__amd__rx7800xt.snap
lact-daemon/src/tests/snapshots/lact_daemon__tests__amd__rx7900xt.snap
lact-daemon/src/tests/snapshots/lact_daemon__tests__amd__rx9070xt-new.snap
lact-daemon/src/tests/snapshots/lact_daemon__tests__amd__rx9070xt.snap
lact-daemon/src/tests/snapshots/lact_daemon__tests__amd__vega56.snap
lact-gui/src/app/pages/thermals_page/fan_curve_frame/mod.rs
lact-gui/src/app/pages/thermals_page/fan_curve_frame/point_adjustment.rs
lact-gui/src/app/pages/thermals_page/mod.rs
lact-schema/src/lib.rs

feat: automatically migrate existing fan curves to be within fan speed limits, show limits in UI

---

res/device_ids.json

Update device_ids with Gigabyte 9070 XT Elite

---

lact-daemon/src/server/gpu_controller/intel.rs

`xe` now exposes package and vram temps separately.

feat: support multiple temperature sensors on intel

---

res/io.github.ilya_zlobintsev.LACT.desktop
res/io.github.ilya_zlobintsev.LACT.metainfo.xml

This PR contains various changes and additions to the metainfo document and desktop file with the goal of improving LACT's appearance on Flathub and in similar app stores.
- Change summary to follow Flathub's (optional) [quality guidelines](https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines)
- Add brand colors for e.g. app banners
- Add donation and help URLs
- Add hardware support information

docs: expand metainfo

---

lact-daemon/src/server/profiles/process.rs

fix: process event iterator handling

---

Cargo.lock
lact-client/src/lib.rs
lact-daemon/src/config.rs
lact-daemon/src/server.rs
lact-daemon/src/server/handler.rs
lact-gui/Cargo.toml
lact-gui/src/app.rs
lact-gui/src/app/header.rs
lact-gui/src/app/header/profile_rename_dialog.rs
lact-gui/src/app/header/profile_row.rs
lact-gui/src/app/msg.rs
lact-schema/src/config.rs
lact-schema/src/request.rs

feat: support exporting and importing profiles

---

lact-daemon/src/server/profiles.rs
lact-gui/src/app.rs
lact-gui/src/app/header.rs
lact-gui/src/app/header/profile_rename_dialog.rs
lact-gui/src/app/header/profile_rule_window.rs
lact-gui/src/app/header/profile_rule_window/profile_row.rs
lact-gui/src/app/msg.rs
lact-schema/src/lib.rs

feat: support profile rules with and/or conditions

---

lact-daemon/src/server/gpu_controller/amd.rs

https://github.com/ilya-zlobintsev/LACT/commit/5007f48208280909adfb7531ac9929ed7aff8fe9#r157969336

fix: use PCIe port link info for AMD GPU

---

Cargo.lock
flatpak/generated-sources.json
lact-daemon/Cargo.toml

Update easy_fuser to v0.4.1

---

lact-daemon/src/server/profiles.rs

Originally added in https://github.com/ilya-zlobintsev/LACT/commit/3f278e7db as a workaround for the process listener randomly stopping to receive notifications, this is no longer needed as the root cause was resolved in #580 .

chore: drop process listener inactivity workaround

---

lact-daemon/src/server/gpu_controller/amd.rs
lact-daemon/src/server/gpu_controller/intel.rs
lact-daemon/src/server/gpu_controller/nvidia.rs
lact-daemon/src/server/vulkan.rs
lact-gui/src/app/pages/software_page.rs
lact-schema/src/lib.rs

feat: allow selecting between multiple vulkan drivers

---

Cargo.lock
lact-cli/Cargo.toml
lact-client/Cargo.toml
lact-daemon/Cargo.toml
lact-daemon/src/system/power_profiles_daemon.rs
lact-gui/Cargo.toml
lact-schema/Cargo.toml
lact/Cargo.toml
pkg/recipes/lact-headless/recipe.yml
pkg/recipes/lact-libadwaita/recipe.yml
pkg/recipes/lact/recipe.yml

Closes https://github.com/ilya-zlobintsev/LACT/issues/640

feat: skip ppd actions disable for tuned-ppd

---

.github/actions/setup-environment/action.yml
.github/workflows/build-packages.yaml

Merge after https://github.com/ilya-zlobintsev/LACT/pull/729

Add cache to CI

---

lact-client/src/lib.rs
lact-daemon/src/bindings.rs
lact-daemon/src/server.rs
lact-daemon/src/server/gpu_controller/amd.rs
lact-daemon/src/server/gpu_controller/common.rs
lact-daemon/src/server/gpu_controller/intel.rs
lact-daemon/src/server/gpu_controller/intel/drm/i915.rs
lact-daemon/src/server/gpu_controller/intel/drm/xe.rs
lact-daemon/src/server/gpu_controller/nvidia.rs
lact-daemon/src/server/gpu_controller/nvidia/driver.rs
lact-daemon/src/server/profiles/process.rs
lact-daemon/src/server/vulkan.rs
lact-daemon/src/system.rs
lact-daemon/src/system/power_profiles_daemon.rs
lact-gui/src/app/graphs_window/stat.rs
lact-schema/src/request.rs

```
cargo +stable clippy --fix
```
and manual fixes

chore: Fix clippy warning from stable

---

lact-gui/i18n/en/lact_gui.ftl
lact-gui/src/app.rs
lact-gui/src/app/header.rs
lact-gui/src/app/pages/oc_page/gpu_stats_section.rs
lact-gui/src/config.rs

feat: configurable stats poll interval

---

lact-daemon/src/server/gpu_controller/intel.rs

fix: correctly write power cap with alternative file name on intel

---

lact-cli/src/lib.rs
lact-cli/src/subcommands.rs
lact-schema/src/args.rs
lact-schema/src/args/cli.rs

Will be merged after #760 to avoid creating conflicts

feat: add power limit subcommand to CLI
